### ISSUE TITLE
Re-enable chromehang symbolication

### ISSUE THREAD

**Issue by vdjeric** [mozilla/Snappy-Symbolication-Server#21]
The server looks stable, let's turn on the heavy symbolication load again and see how well it copes

**Comment by mreid-moz** [comment]
Thundering herd incoming tomorrow :)

**Comment by vdjeric** [comment]
Looks like it didn't handle it too well :/

2015-08-27 21:39:12,260 DEBUG   24366   Loading [ws2_32.pdb] [18C960B958404C4F80F686EE978A33D42] from <class 'symCache.DiskCache'>
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/**init**.py", line 875, in emit
    self.flush()
  File "/usr/lib64/python2.7/logging/**init**.py", line 835, in flush
    self.stream.flush()
IOError: [Errno 28] No space left on device

**Comment by vdjeric** [comment]
I fixed additional issues in #22, let's see how it holds up tomorrow :)
